package org.openpnp.libuvc4j;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.openpnp.libuvc4j.UvcLibrary.uvc_it_type;
/**
 * <i>native declaration : /usr/local/Cellar/libuvc/HEAD/include/libuvc/libuvc.h:246</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("uvc") 
public class uvc_input_terminal extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : uvc_input_terminal* */
	@Field(0) 
	public Pointer<uvc_input_terminal > prev() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : uvc_input_terminal* */
	@Field(0) 
	public uvc_input_terminal prev(Pointer<uvc_input_terminal > prev) {
		this.io.setPointerField(this, 0, prev);
		return this;
	}
	/** C type : uvc_input_terminal* */
	@Field(1) 
	public Pointer<uvc_input_terminal > next() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : uvc_input_terminal* */
	@Field(1) 
	public uvc_input_terminal next(Pointer<uvc_input_terminal > next) {
		this.io.setPointerField(this, 1, next);
		return this;
	}
	@Field(2) 
	public byte bTerminalID() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public uvc_input_terminal bTerminalID(byte bTerminalID) {
		this.io.setByteField(this, 2, bTerminalID);
		return this;
	}
	/** C type : uvc_it_type */
	@Field(3) 
	public IntValuedEnum<uvc_it_type > wTerminalType() {
		return this.io.getEnumField(this, 3);
	}
	/** C type : uvc_it_type */
	@Field(3) 
	public uvc_input_terminal wTerminalType(IntValuedEnum<uvc_it_type > wTerminalType) {
		this.io.setEnumField(this, 3, wTerminalType);
		return this;
	}
	@Field(4) 
	public short wObjectiveFocalLengthMin() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public uvc_input_terminal wObjectiveFocalLengthMin(short wObjectiveFocalLengthMin) {
		this.io.setShortField(this, 4, wObjectiveFocalLengthMin);
		return this;
	}
	@Field(5) 
	public short wObjectiveFocalLengthMax() {
		return this.io.getShortField(this, 5);
	}
	@Field(5) 
	public uvc_input_terminal wObjectiveFocalLengthMax(short wObjectiveFocalLengthMax) {
		this.io.setShortField(this, 5, wObjectiveFocalLengthMax);
		return this;
	}
	@Field(6) 
	public short wOcularFocalLength() {
		return this.io.getShortField(this, 6);
	}
	@Field(6) 
	public uvc_input_terminal wOcularFocalLength(short wOcularFocalLength) {
		this.io.setShortField(this, 6, wOcularFocalLength);
		return this;
	}
	@Field(7) 
	public long bmControls() {
		return this.io.getLongField(this, 7);
	}
	@Field(7) 
	public uvc_input_terminal bmControls(long bmControls) {
		this.io.setLongField(this, 7, bmControls);
		return this;
	}
	public uvc_input_terminal() {
		super();
	}
	public uvc_input_terminal(Pointer pointer) {
		super(pointer);
	}
}
