package org.openpnp.libuvc4j;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /usr/local/Cellar/libuvc/HEAD/include/libuvc/libuvc.h:299</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("uvc") 
public class uvc_device_descriptor extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short idVendor() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public uvc_device_descriptor idVendor(short idVendor) {
		this.io.setShortField(this, 0, idVendor);
		return this;
	}
	@Field(1) 
	public short idProduct() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public uvc_device_descriptor idProduct(short idProduct) {
		this.io.setShortField(this, 1, idProduct);
		return this;
	}
	@Field(2) 
	public short bcdUVC() {
		return this.io.getShortField(this, 2);
	}
	@Field(2) 
	public uvc_device_descriptor bcdUVC(short bcdUVC) {
		this.io.setShortField(this, 2, bcdUVC);
		return this;
	}
	/** C type : const char* */
	@Field(3) 
	public Pointer<Byte > serialNumber() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : const char* */
	@Field(3) 
	public uvc_device_descriptor serialNumber(Pointer<Byte > serialNumber) {
		this.io.setPointerField(this, 3, serialNumber);
		return this;
	}
	/** C type : const char* */
	@Field(4) 
	public Pointer<Byte > manufacturer() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : const char* */
	@Field(4) 
	public uvc_device_descriptor manufacturer(Pointer<Byte > manufacturer) {
		this.io.setPointerField(this, 4, manufacturer);
		return this;
	}
	/** C type : const char* */
	@Field(5) 
	public Pointer<Byte > product() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : const char* */
	@Field(5) 
	public uvc_device_descriptor product(Pointer<Byte > product) {
		this.io.setPointerField(this, 5, product);
		return this;
	}
	public uvc_device_descriptor() {
		super();
	}
	public uvc_device_descriptor(Pointer pointer) {
		super(pointer);
	}
}
