package org.openpnp.libuvc4j;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /usr/local/Cellar/libuvc/HEAD/include/libuvc/libuvc.h:258</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("uvc") 
public class uvc_processing_unit extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : uvc_processing_unit* */
	@Field(0) 
	public Pointer<uvc_processing_unit > prev() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : uvc_processing_unit* */
	@Field(0) 
	public uvc_processing_unit prev(Pointer<uvc_processing_unit > prev) {
		this.io.setPointerField(this, 0, prev);
		return this;
	}
	/** C type : uvc_processing_unit* */
	@Field(1) 
	public Pointer<uvc_processing_unit > next() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : uvc_processing_unit* */
	@Field(1) 
	public uvc_processing_unit next(Pointer<uvc_processing_unit > next) {
		this.io.setPointerField(this, 1, next);
		return this;
	}
	@Field(2) 
	public byte bUnitID() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public uvc_processing_unit bUnitID(byte bUnitID) {
		this.io.setByteField(this, 2, bUnitID);
		return this;
	}
	@Field(3) 
	public byte bSourceID() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public uvc_processing_unit bSourceID(byte bSourceID) {
		this.io.setByteField(this, 3, bSourceID);
		return this;
	}
	@Field(4) 
	public long bmControls() {
		return this.io.getLongField(this, 4);
	}
	@Field(4) 
	public uvc_processing_unit bmControls(long bmControls) {
		this.io.setLongField(this, 4, bmControls);
		return this;
	}
	public uvc_processing_unit() {
		super();
	}
	public uvc_processing_unit(Pointer pointer) {
		super(pointer);
	}
}
