package org.openpnp.libuvc4j;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.openpnp.libuvc4j.UvcLibrary.uvc_device_handle;
import org.openpnp.libuvc4j.UvcLibrary.uvc_frame_format;
/**
 * <i>native declaration : /usr/local/Cellar/libuvc/HEAD/include/libuvc/libuvc.h:317</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("uvc")
// Removed abstract, otherwise dereferencing pointers of this type fails.
public class uvc_frame extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : void* */
	@Field(0) 
	public Pointer<? > data() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : void* */
	@Field(0) 
	public uvc_frame data(Pointer<? > data) {
		this.io.setPointerField(this, 0, data);
		return this;
	}
	@Ptr 
	@Field(1) 
	public long data_bytes() {
		return this.io.getSizeTField(this, 1);
	}
	@Ptr 
	@Field(1) 
	public uvc_frame data_bytes(long data_bytes) {
		this.io.setSizeTField(this, 1, data_bytes);
		return this;
	}
	@Field(2) 
	public int width() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public uvc_frame width(int width) {
		this.io.setIntField(this, 2, width);
		return this;
	}
	@Field(3) 
	public int height() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public uvc_frame height(int height) {
		this.io.setIntField(this, 3, height);
		return this;
	}
	/** C type : uvc_frame_format */
	@Field(4) 
	public IntValuedEnum<uvc_frame_format > frame_format() {
		return this.io.getEnumField(this, 4);
	}
	/** C type : uvc_frame_format */
	@Field(4) 
	public uvc_frame frame_format(IntValuedEnum<uvc_frame_format > frame_format) {
		this.io.setEnumField(this, 4, frame_format);
		return this;
	}
	@Ptr 
	@Field(5) 
	public long step() {
		return this.io.getSizeTField(this, 5);
	}
	@Ptr 
	@Field(5) 
	public uvc_frame step(long step) {
		this.io.setSizeTField(this, 5, step);
		return this;
	}
	@Field(6) 
	public int sequence() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public uvc_frame sequence(int sequence) {
		this.io.setIntField(this, 6, sequence);
		return this;
	}
	/** Conversion Error : timeval (failed to convert type to Java (undefined type)) */
	/** C type : uvc_device_handle_t* */
	@Field(8) 
	public Pointer<uvc_device_handle > source() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : uvc_device_handle_t* */
	@Field(8) 
	public uvc_frame source(Pointer<uvc_device_handle > source) {
		this.io.setPointerField(this, 8, source);
		return this;
	}
	@Field(9) 
	public byte library_owns_data() {
		return this.io.getByteField(this, 9);
	}
	@Field(9) 
	public uvc_frame library_owns_data(byte library_owns_data) {
		this.io.setByteField(this, 9, library_owns_data);
		return this;
	}
}
