package org.openpnp.libuvc4j;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /usr/local/Cellar/libuvc/HEAD/include/libuvc/libuvc.h:345</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("uvc") 
public class uvc_stream_ctrl extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short bmHint() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public uvc_stream_ctrl bmHint(short bmHint) {
		this.io.setShortField(this, 0, bmHint);
		return this;
	}
	@Field(1) 
	public byte bFormatIndex() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public uvc_stream_ctrl bFormatIndex(byte bFormatIndex) {
		this.io.setByteField(this, 1, bFormatIndex);
		return this;
	}
	@Field(2) 
	public byte bFrameIndex() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public uvc_stream_ctrl bFrameIndex(byte bFrameIndex) {
		this.io.setByteField(this, 2, bFrameIndex);
		return this;
	}
	@Field(3) 
	public int dwFrameInterval() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public uvc_stream_ctrl dwFrameInterval(int dwFrameInterval) {
		this.io.setIntField(this, 3, dwFrameInterval);
		return this;
	}
	@Field(4) 
	public short wKeyFrameRate() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public uvc_stream_ctrl wKeyFrameRate(short wKeyFrameRate) {
		this.io.setShortField(this, 4, wKeyFrameRate);
		return this;
	}
	@Field(5) 
	public short wPFrameRate() {
		return this.io.getShortField(this, 5);
	}
	@Field(5) 
	public uvc_stream_ctrl wPFrameRate(short wPFrameRate) {
		this.io.setShortField(this, 5, wPFrameRate);
		return this;
	}
	@Field(6) 
	public short wCompQuality() {
		return this.io.getShortField(this, 6);
	}
	@Field(6) 
	public uvc_stream_ctrl wCompQuality(short wCompQuality) {
		this.io.setShortField(this, 6, wCompQuality);
		return this;
	}
	@Field(7) 
	public short wCompWindowSize() {
		return this.io.getShortField(this, 7);
	}
	@Field(7) 
	public uvc_stream_ctrl wCompWindowSize(short wCompWindowSize) {
		this.io.setShortField(this, 7, wCompWindowSize);
		return this;
	}
	@Field(8) 
	public short wDelay() {
		return this.io.getShortField(this, 8);
	}
	@Field(8) 
	public uvc_stream_ctrl wDelay(short wDelay) {
		this.io.setShortField(this, 8, wDelay);
		return this;
	}
	@Field(9) 
	public int dwMaxVideoFrameSize() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public uvc_stream_ctrl dwMaxVideoFrameSize(int dwMaxVideoFrameSize) {
		this.io.setIntField(this, 9, dwMaxVideoFrameSize);
		return this;
	}
	@Field(10) 
	public int dwMaxPayloadTransferSize() {
		return this.io.getIntField(this, 10);
	}
	@Field(10) 
	public uvc_stream_ctrl dwMaxPayloadTransferSize(int dwMaxPayloadTransferSize) {
		this.io.setIntField(this, 10, dwMaxPayloadTransferSize);
		return this;
	}
	@Field(11) 
	public int dwClockFrequency() {
		return this.io.getIntField(this, 11);
	}
	@Field(11) 
	public uvc_stream_ctrl dwClockFrequency(int dwClockFrequency) {
		this.io.setIntField(this, 11, dwClockFrequency);
		return this;
	}
	@Field(12) 
	public byte bmFramingInfo() {
		return this.io.getByteField(this, 12);
	}
	@Field(12) 
	public uvc_stream_ctrl bmFramingInfo(byte bmFramingInfo) {
		this.io.setByteField(this, 12, bmFramingInfo);
		return this;
	}
	@Field(13) 
	public byte bPreferredVersion() {
		return this.io.getByteField(this, 13);
	}
	@Field(13) 
	public uvc_stream_ctrl bPreferredVersion(byte bPreferredVersion) {
		this.io.setByteField(this, 13, bPreferredVersion);
		return this;
	}
	@Field(14) 
	public byte bMinVersion() {
		return this.io.getByteField(this, 14);
	}
	@Field(14) 
	public uvc_stream_ctrl bMinVersion(byte bMinVersion) {
		this.io.setByteField(this, 14, bMinVersion);
		return this;
	}
	@Field(15) 
	public byte bMaxVersion() {
		return this.io.getByteField(this, 15);
	}
	@Field(15) 
	public uvc_stream_ctrl bMaxVersion(byte bMaxVersion) {
		this.io.setByteField(this, 15, bMaxVersion);
		return this;
	}
	@Field(16) 
	public byte bInterfaceNumber() {
		return this.io.getByteField(this, 16);
	}
	@Field(16) 
	public uvc_stream_ctrl bInterfaceNumber(byte bInterfaceNumber) {
		this.io.setByteField(this, 16, bInterfaceNumber);
		return this;
	}
	public uvc_stream_ctrl() {
		super();
	}
	public uvc_stream_ctrl(Pointer pointer) {
		super(pointer);
	}
}
